spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug


